language: node_js
node_js:
- '5'
before_script:
- npm install -g bower
- npm install -g harp
- bower install
- npm install
- chmod +x ./deploy.sh
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/jordancolburn/suitcasestudio.git
  - secure: tfrmF+H3LAhV9MKdgkWHe9CyIeHOQl87U5mNr4TveUgP1nnglmEKiyjXmQ92eWg+zMMcc+jQrZ7m4upfDOBsnmJxAzHLZaNSKGlsn3MtDia6pi4U8+CPK2JFWfuMuqlhJnkfI9CLmPi7dI8nAKhmi3YwpV8nDx/3AC0inx6VkdP+jEUO8irkY3kQe4suZ/AblhyY5v7bqCFc8Zd1r6EpH7Ghc3J+5ZlS09PisdPda/aaFIg41zr+EDfPm8Wi8g9lVH3OgUVGEUf68uziL+R4LHc1UlIBm61jEkroncJo036B4pq6rNUVHt3mf7Au1cHx4z6mknJH5DtIb7N4Hr053HCT5oiiD1VFW1OwApZxDTQcxIevy/4xSBsyhks2suxv4DSLpARhpYs1Jpci0Tn7rw8BhZg3G13IW3AF+Bo7duSQGaSAXrYNQxZ+01mINaEz3XUZziYv7wrBSX+mtoBI9J4JcHX/o+YgffHn10XZAdojd9V0Y+a5S6vLelEnmzjKOw+T0RlfsaL6F6L7ano2NMaYtjZONG5LJC7QZzcJZ722zROmRGZqhmB9Nh20VdTBrGc4guAPMQPqgRaG5dB6KeiEsX+0mmpHr8aw5iD0rV/BcI6IiVr7er+PEgdnE0+c8ocKw7tzaUmJ3yact3gCrL5mdeJhvePRP4Wh1Ec8dB0=
