language: node_js
node_js:
  - '5'
before_script:  
  - npm install -g bower
  - npm install -g harp
  - bower install
  - npm install
  - chmod +x ./deploy.sh
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/jordancolburn/suitcasestudio.git
  - secure: a4qZanNpNlkK/sZZ6XraJ1bMHUw/PkVWZmQTDalCnH8v+6HricgSdzRqrJjvR0H+/9biULWAiJrhJWd89QMEduNYnHDLzM7k66cgrk1qKyXDro/05yLsjmxBVvOO0Izd9zkzEDHd2KU/nR0P38KU5vyaE73eReRaYs7urh/3PUGN7tr5Rwc1fOxEPndSoU8Vcvx9FX/6xfH/xLKAlAumKfdzx0mvtY38g3uAdw0WnojnCWrH/Z1sqA7DFkJYK9mxd7cvqvdkypH5tYscT+XZosc3rd6JfY0Gl+eZE4Zns9j+OswouVeKT/WoE9hLnIfR1+FY5HsjcyDAa9s9zJ8quWTzfI9NUftFEv/9xT7+2nabWMSrMf5YVdf6zgiMABtTTHFdhsj3e06JwLqCqX7/A+380vwvPkBUcuMVGapjXrSYi1wP4rr1+6HZ5pyuP6gkW8lr20pgsnGvo1bsLlxXoPekO0vWt2KTgaAltZAo8UQX93ig850qcErfd35+zbHW/GRqVLPnVP7VU9VRiQEvDK5JiY8C6XM3cLnST4pW0gqZXdD+AjUaMnE6Kho7wnEu14/9GiFFhqOTxaJ3STW1L7lh11pERe/I9TEncyXuxes/AMXu2v4ia+pDY4b4rX0oJnfo11OU2FxWMQJTXFZExL3ui9bdRB8YjpwARCsFzT0=
