language: node_js
node_js:
  - '5'
before_script:  
  - npm install -g bower
  - npm install -g harp
  - bower install
  - npm install
  - chmod +x ./deploy.sh
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/jordancolburn/suitcasestudio.git
  - secure: "g0lXYC6BAYWvGaNLZST1Yi7SaAW03DGXDL0WTw2lym8pK17e1GIE1tLkedX7ZGWnCtPM1StfAhMYHch1qi+GCMWtagtTmSf0LxEPUPgo6JvblX013fwYh1B4KuTp3HmcKlRuDoeLNAfN9ORpDg1pFcmdzm+z3RPTDOs3V1FYKrvFdDtlc6thVeJpONJR+6xalgl8UQOPZ7tqlR9TyR4UmfePoqVHAh/KSEFds8KCgHMsay24Pe41t9qjJ0Pwi4ma3S8sv0+sIAobAUqnFtA4Gbk87geABNpfbIih86+RbOBjPvHa9HCWOUnvKSiz8Cl5F5IMhiv0ZJYwpIdj+th93HtkrHLQiGQQW/8tOowRNQmcQKcoEQiIlOey/oqEGEpAcGTiQZ+4CrHOvCXChaHrXgoD2SRTZjEqiObxpGE7WByt82vq6ZtclDWv6P4xxiwBPymIWlP900tp2ZTd2t9D4rQaB1A+YdigqWJFgQcGAgUf9tWGNCfg9UNhXdn4pK8sRDY3iJvoioRp+SCMKGT6T1ei2J3IT5aWoEgIHZrhgu6KosqCr+3D/R6z5MsiPtV+4WV/UugqwNtaXGQmVeXaWXiqAl5UbpR0j7ZOgdTg1TOUnrCbWZmVlScXu1IEpa3gGDkFLPOvsFxZeYeID5C6vVOAsySVezr/xugqJQfoTS4="
