language: node_js
node_js:
- '5'
before_script:
- npm install -g bower
- npm install -g harp
- bower install
- npm install
- chmod +x ./deploy.sh
script: bash ./deploy.sh
env:
  global:
  - DOMAIN_NAME: www.suitcasestudiomusic.com
  - GH_REF: github.com/jordancolburn/suitcasestudio.git
  - secure: ZapOpQbCb8PnRB/V1bRn6Z1Q/fDZTt11LNSpv/e0U8cLKicHHm0j3aDt5VSL9c5eossk7+fUTFMdO3Bke3ty0rWydZKGm3GQSNCvwjrvjKO4vM6jSTM9Avftt2OJBc3DSgbdCGQX0fR6TGe3GHoLOXfoYEUHVNFZ5hUgDdpr1zDPSPi1nKQXsep2E5FPhbquzd0+CBbEsqGVcuJQFwZQtqSn9DA4jh6dIc5PiMxSBzGlJByTEZyF+cuF37RxCNg+yRQC8vyYQASfreJtG70Z8ythk8FI51wpQEHMWhareLvZE8TPBQ1dZM4M5urcAQc6kU9m931RhrSnH5tmQLPSMkbYagtLKkrZ4aOAklRO+N0/Y3a42OGt2YMSnWJ8Rce/akyin5+5W7HcCK3/zWmXCvrnIxFnHrDfDGbqY8AW86Q5jrNKYIzeyHKdMHvNul9mqWrwdj3Fc38qCmEgf+w/KCEritkGJkUVPP9gbtjJrsYFNwFS31Kio1mWHYieQcMHKudyNJkUQSqBKd5NPM/WFJCmnengWg2QdlrEHvB/+xlRrklgrDMX0JGI4vNq13rpyBFTu+D1+i2yNyv8130AgSlZzCZHpQa+8OB0Ut9F2uuCesw0MvZyBEaHHT5PB0PXrQ2DG0mQMvoChB8pUuENBfTLjQYz5PJdCBQkOu6FlfM=
